name: shipit
on:
  release:	
    types:	
      - "published"	
      - "edited"
      - "prereleased"
  push:
    branches:
      - "master"
      - "actions/release-android__*"
    paths:
      - "pubspec.yaml"
      - "android/**"
      - "lib/**"
      - ".github/workflows/shipit.yml"
jobs:
  release-android:
    name: release android app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.21.0-7.0.pre'
          channel: 'dev'
      - name: Install gem packages
        run: |
          cd android
          gem install bundler:1.17.3
          bundle install
          bundle exec fastlane install_plugins
          bundle exec fastlane update_plugins
      - name: Build apk and app bundle package
        env:
          ANDROID_KEY_PWD: ${{ secrets.ANDROID_KEY_PWD }}
          ANDROID_KEY_STORE_PWD: ${{ secrets.ANDROID_KEY_STORE_PWD }}
          RELEASE_KEYSTORE: ${{ secrets.RELEASE_KEYSTORE }}
          RELEASE_KEYSTORE_PASSPHRASE: ${{ secrets.RELEASE_KEYSTORE_PASSPHRASE }}
          RELEASE_SERVICE_ACCOUNT_KEYSTORE: ${{ secrets.RELEASE_SERVICE_ACCOUNT_KEYSTORE }}
        run: |
          ./scripts/setenv.sh
          flutter pub get
          flutter build appbundle
      - name: Upload app to Google Play Store
        env:
          ANDROID_KEY_PWD: ${{ secrets.ANDROID_KEY_PWD }}
          ANDROID_KEY_STORE_PWD: ${{ secrets.ANDROID_KEY_STORE_PWD }}
          RELEASE_KEYSTORE: ${{ secrets.RELEASE_KEYSTORE }}
          RELEASE_KEYSTORE_PASSPHRASE: ${{ secrets.RELEASE_KEYSTORE_PASSPHRASE }}
          RELEASE_SERVICE_ACCOUNT_KEYSTORE: ${{ secrets.RELEASE_SERVICE_ACCOUNT_KEYSTORE }}
        run: |
          ./scripts/setenv.sh
          cd android/
          bundle exec fastlane internal
      - name: Promote to alpha
        env:
          ANDROID_KEY_PWD: ${{ secrets.ANDROID_KEY_PWD }}
          ANDROID_KEY_STORE_PWD: ${{ secrets.ANDROID_KEY_STORE_PWD }}
          RELEASE_KEYSTORE: ${{ secrets.RELEASE_KEYSTORE }}
          RELEASE_KEYSTORE_PASSPHRASE: ${{ secrets.RELEASE_KEYSTORE_PASSPHRASE }}
          RELEASE_SERVICE_ACCOUNT_KEYSTORE: ${{ secrets.RELEASE_SERVICE_ACCOUNT_KEYSTORE }}
        run: |
          ./scripts/setenv.sh
          cd android/
          bundle exec fastlane alpha
      - name: Promote to beta
        if: contains(github.event_name,'release')
        env:
          ANDROID_KEY_PWD: ${{ secrets.ANDROID_KEY_PWD }}
          ANDROID_KEY_STORE_PWD: ${{ secrets.ANDROID_KEY_STORE_PWD }}
          RELEASE_KEYSTORE: ${{ secrets.RELEASE_KEYSTORE }}
          RELEASE_KEYSTORE_PASSPHRASE: ${{ secrets.RELEASE_KEYSTORE_PASSPHRASE }}
          RELEASE_SERVICE_ACCOUNT_KEYSTORE: ${{ secrets.RELEASE_SERVICE_ACCOUNT_KEYSTORE }}
        run: |
          ./scripts/setenv.sh
          cd android/
          bundle exec fastlane beta
      - name: Promote to production
        if: contains(github.event_name,'release')&&(!github.event.release.prerelease)
        env:
          ANDROID_KEY_PWD: ${{ secrets.ANDROID_KEY_PWD }}
          ANDROID_KEY_STORE_PWD: ${{ secrets.ANDROID_KEY_STORE_PWD }}
          RELEASE_KEYSTORE: ${{ secrets.RELEASE_KEYSTORE }}
          RELEASE_KEYSTORE_PASSPHRASE: ${{ secrets.RELEASE_KEYSTORE_PASSPHRASE }}
          RELEASE_SERVICE_ACCOUNT_KEYSTORE: ${{ secrets.RELEASE_SERVICE_ACCOUNT_KEYSTORE }}
        run: |
          ./scripts/setenv.sh
          cd android/
          bundle exec fastlane production
